spring:
   application:
     name: Emp-Service
   datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: girish_007
        url: jdbc:mysql://localhost:3306/employee_db
        username: root
   jpa:    
        hibernate:                
            ddl-auto: update  
        show_sql: true  
                     
#server:
#  port: 8001
#  servlet:
#    context-path: /empservice
#eureka:
#  client:
#   serviceUrl:
#    defaultZone: http://localhost:8761/eureka/
#    register-with-eureka: true
#    fetch-registry: false
#  instance:
#      preferIpAddress: true  

 
    
    




