spring:
   application:
     name: Emp-Service
   datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: girish_007
        url: jdbc:mysql://localhost:3306/employee_db
        username: root
   jpa:    
        hibernate:                
            ddl-auto: update  
        show_sql: true
   profiles:
        active: dev
   config:
        import: optional:configserver:http://localhost:8888 
        name: emp-service
   mvc:
        problemdetails:
                     enabled: true     
            
                     
server:
  port: 8001
  servlet:
    context-path: /emp-service
eureka:
  client:
   serviceUrl:
    defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: false
  instance:
      preferIpAddress: true       
        
logging:
   file:
    name: logs/app.log      
   logback:
    rollingpolicy:
     file-name-pattern: logs/%d{yyyy-MM, aux}/app.%d{yyyy-MM-dd}.%i.log 
     max-file-size: 100MB
     total-size-cap: 10GB
     max-history: 10

resilience4j:
    ratelimiter:
      instances:
         getEmployeeRateLimit:
           limit-for-period: 2
           limit-refresh-period: 5s
           timeout-duration: 0             
    retry:
       instances:
         getRetryEmployeesList:
           max-attempts: 5
           wait-duration: 2s
           retry-exceptions: org.springframework.web.client.ResourceAccessException           
    circuitbreaker:
      instances:
         saveEmpCircuitBreaker:
           failure-rate-threshold: 80
           sliding-window-size: 10
           sliding-window-type: COUNT_BASED
           minimum-number-of-calls: 5
           automatic-transition-from-open-to-half-open-enabled: true
           permitted-number-of-calls-in-half-open-state: 4
           wait-duration-in-open-state: 1s          
#    timelimiter:
#       instances:
#          updateEmpTimeLimitter:
#           timeout-duration: 1ms
#           cancel-running-future: false         
    bulkhead:
        instances:
          getMessageBulkHead:
           max-concurrent-calls: 5
           max-wait-duration: 0
management:
  endpoint:
    shutdown:
      enabled: false
    info:
      enabled: true
    caches:
      cache:
        time-to-live: 10s
    health:
      show-details: always
      show-components: always
      group:
        custom:
         show-details: always
         roles: admin         
  endpoints:
    enabled-by-default: true
    jmx:
      exposure:
        include: health,info
    web:
      cors:
        allowed-methods: GET,POST,PUT,DELETE
        allowed-origins: http://localhost:8001/emp-service/
      
  metrics:
    use-global-registry: false           
       